namespace OnboardMe.Web.Services.RepoIngestion;

/// <summary>A grounded answer returned by the chat service.</summary>
public sealed class ChatAnswer
{
    /// <summary>The answer text generated by the model.</summary>
    public required string Answer { get; init; }

    /// <summary>File-path citations extracted from the context chunks used to produce the answer.</summary>
    public required IReadOnlyList<FileCitation> Citations { get; init; }

    /// <summary>
    /// When <see langword="true"/> the model could not produce a grounded answer and instead
    /// returned a focused clarification question. Citations will be empty in this case.
    /// </summary>
    public bool IsClarification { get; init; }
}

/// <summary>A reference to a specific location in the repository that supported the answer.</summary>
public sealed class FileCitation
{
    /// <summary>Repository-relative file path (e.g. <c>src/App.cs</c>).</summary>
    public required string Path { get; init; }

    /// <summary>Inclusive start line of the cited chunk (1-based).</summary>
    public required int StartLine { get; init; }

    /// <summary>Inclusive end line of the cited chunk (1-based).</summary>
    public required int EndLine { get; init; }
}
